"""Initial migration

Revision ID: c85ba6a368c2
Revises: 
Create Date: 2026-03-26 10:23:22.593448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85ba6a368c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_guid', sa.String(length=36), nullable=True),
    sa.Column('data_subject_guid', sa.String(length=36), nullable=True),
    sa.Column('receipt_token', sa.String(length=255), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor_guid'), ['actor_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_data_subject_guid'), ['data_subject_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_receipt_token'), ['receipt_token'], unique=False)

    op.create_table('guid_resolution_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('source_guid', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('resolved_json', sa.JSON(), nullable=True),
    sa.Column('fetched_from', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('guid_resolution_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guid_resolution_cache_source_guid'), ['source_guid'], unique=False)

    op.create_table('inbound_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('service_request_guid', sa.String(length=36), nullable=False),
    sa.Column('transaction_guid', sa.String(length=36), nullable=True),
    sa.Column('concept_guid', sa.String(length=36), nullable=True),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('provider_org_guid', sa.String(length=36), nullable=False),
    sa.Column('contract_guid', sa.String(length=36), nullable=False),
    sa.Column('grant_token', sa.String(length=64), nullable=True),
    sa.Column('fhir_observation_json', sa.JSON(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('resolution_status', sa.String(length=20), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('inbound_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_observations_concept_guid'), ['concept_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_observations_contract_guid'), ['contract_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_observations_patient_guid'), ['patient_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_observations_provider_org_guid'), ['provider_org_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_observations_service_request_guid'), ['service_request_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_observations_transaction_guid'), ['transaction_guid'], unique=False)

    op.create_table('service_request_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('service_request_guid', sa.String(length=36), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('provider_org_guid', sa.String(length=36), nullable=False),
    sa.Column('contract_guid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected_transactions', sa.Integer(), nullable=True),
    sa.Column('delivered_transactions', sa.Integer(), nullable=False),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('grant_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('service_request_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_request_status_patient_guid'), ['patient_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_request_status_provider_org_guid'), ['provider_org_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_request_status_service_request_guid'), ['service_request_guid'], unique=True)

    op.create_table('observation_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('observation_guid', sa.String(length=36), nullable=False),
    sa.Column('careplan_guid', sa.String(length=36), nullable=True),
    sa.Column('plandef_guid', sa.String(length=36), nullable=True),
    sa.Column('transaction_guid', sa.String(length=36), nullable=True),
    sa.Column('resolved_context_json', sa.JSON(), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('vector_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['observation_guid'], ['inbound_observations.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('observation_vectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_vectors_careplan_guid'), ['careplan_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_vectors_observation_guid'), ['observation_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_vectors_plandef_guid'), ['plandef_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_vectors_transaction_guid'), ['transaction_guid'], unique=False)

    op.create_table('validation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('observation_guid', sa.String(length=36), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['observation_guid'], ['inbound_observations.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('validation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_log_observation_guid'), ['observation_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_log_observation_guid'))

    op.drop_table('validation_log')
    with op.batch_alter_table('observation_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_vectors_transaction_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_vectors_plandef_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_vectors_observation_guid'))
        batch_op.drop_index(batch_op.f('ix_observation_vectors_careplan_guid'))

    op.drop_table('observation_vectors')
    with op.batch_alter_table('service_request_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_request_status_service_request_guid'))
        batch_op.drop_index(batch_op.f('ix_service_request_status_provider_org_guid'))
        batch_op.drop_index(batch_op.f('ix_service_request_status_patient_guid'))

    op.drop_table('service_request_status')
    with op.batch_alter_table('inbound_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_observations_transaction_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_observations_service_request_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_observations_provider_org_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_observations_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_observations_contract_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_observations_concept_guid'))

    op.drop_table('inbound_observations')
    with op.batch_alter_table('guid_resolution_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guid_resolution_cache_source_guid'))

    op.drop_table('guid_resolution_cache')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_receipt_token'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_data_subject_guid'))
        batch_op.drop_index(batch_op.f('ix_audit_log_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_guid'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
